service: gemini-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  timeout: 10

functions:
  askGemini:
    handler: handler.askGemini
    events:
      - http:
          path: geminiQueryHandler
          method: post
          cors: true
  
  recommendForYou:
    handler: lambda/recommendForYou.recommendForYou
    events:
      - http:
          path: /for-you
          method: get

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    basePath: ./